### ISSUE TITLE
[BUG] 홈페이지 접속 시 에러

### ISSUE THREAD

**Issue by Choi-JJunho** [woowacourse-teams/2023-votogether#268]
### 버그 사항
https://votogether.com/ 홈페이지에 접속하면 약 5초뒤에 해당 에러페이지가 등장합니다.
 
### 버그 simulation
> 버그를 발견하게 된 상황을 단계별로 적어주세요 😊

1. 접속
2. 대기
3. 에러발생

### 원하던 상황
> 원했던 상황을 자세하게 적어주세요 😊
 
접속하고 사이트의 정보를 보고싶어요

### **Screenshots**
![image](https://github.com/woowacourse-teams/2023-votogether/assets/49794401/6dac0164-2b9b-4125-b421-b425f29bba62)

**Comment by inyeong-kang** [comment]
비회원으로 게시글 목록 조회하는 API가 아직 구현되지 않아서, 해당 API가 구현되면 close하도록 하겠습니다. 감사합니다😃👍
