### ISSUE TITLE
[BUG] 마감 시간 선택이 어렵습니다

### ISSUE THREAD

**Issue by WaiNaat** [woowacourse-teams/2023-votogether#283]
### 버그 사항

마감 시간 선택하는 다이얼? 조작이 잘 안 됩니다

### 버그 simulation

클릭하면 넘어가는 것 같은데 어디를 눌러야 하는지 잘 모르겠습니다
일단 글자 클릭으로는 안 되는 것 같아요

### 원하던 상황

마우스로 원활하게 넘어갈 수 있으면 좋겠습니다

### **Screenshots**

![날짜 선택](https://github.com/woowacourse-teams/2023-votogether/assets/77872742/01deea8e-3b84-4fd5-8ddd-98e90ae9229f)

**Comment by inyeong-kang** [comment]
https://github.com/woowacourse-teams/2023-votogether/pull/201 에서 반영 완료✅
