### ISSUE TITLE
[BUG] 마감된 게시글 투표 에러 메시지

### ISSUE THREAD

**Issue by Gilpop8663** [woowacourse-teams/2023-votogether#473]
### 버그 사항

애초에 마감된 게시글에 투표를 시도할 경우엔 예외 메시지가 잘 나옵니다.

그런데 마감되지 않은 상태에서, 투표하려 하는데 그 사이에 마감이 되어버리고 새로고침을 안한 상태로 투표를 하면 에러 메시지에 불필요한 정보까지 같이 딸려오는 현상이 보입니다.

### 원하던 상황

에러 메세지가 올바르게 나오면 좋겠어요

### **Screenshots**

https://votogether.com/posts/84

**Comment by inyeong-kang** [comment]
![image](https://github.com/woowacourse-teams/2023-votogether/assets/81199414/fd25ef3f-e643-4f95-a8a9-9a96281d4bb5)
