### ISSUE TITLE
[BUG] 로그인되어있는 상태로 쿠키가 만료되면 로그아웃이 안될 것으로 추정됨

### ISSUE THREAD

**Issue by chsua** [woowacourse-teams/2023-votogether#485]
### 버그 사항
로그인되어있는 상태로 쿠키가 만료되면 로그아웃이 안될 것으로 추정됨
현재 로직으로는 쿠키가 있으면 자동 로그인을 하는데,
만약 로그인을 한 채로 쿠키가 만료되면
쿠키는 사라졌지만 로그인을 풀리지 않는 오류가 발생할 것으로 예상됨
 

### 버그 simulation
다른 팀들 로그인 이야기 듣다가 깨닮
 

### 원하던 상황
쿠키 만료시 로그아웃처리

**Comment by Gilpop8663** [comment]
리프래시 토큰이 생기면 로그인 되어 있는 상태로 쿠키가 만료되지 않을것이라고 생각하여 추가적인 코드를 작성하지 않으려고 합니다
