### ISSUE TITLE
Carousel 컴포넌트 구현, 공지사항 배너에 적용

### ISSUE THREAD

**Issue by inyeong-kang** [woowacourse-teams/2023-votogether#596]
## ✨ 추가 기능
Carousel 컴포넌트를 구현하고 공지사항 배너에 적용합니다.

## 📆 일정 추정
3시간

## 📃 세부 사항
공지사항이 여러개인 경우를 위해 Carousel 컴포넌트로 공지사항을 보여주도록 합니다.

## ✅ 투두리스트

- [ ] Carousel 컴포넌트 구현
- [ ] 공지사항 배너 Carousel 로 리팩터링

## 🔗 참고 자료
![image](https://github.com/woowacourse-teams/2023-votogether/assets/81199414/e843783e-b893-40e8-9cf0-a67cec3a133c)
![image](https://github.com/woowacourse-teams/2023-votogether/assets/81199414/38aeaee9-440a-4a73-af64-56fcc7def3ad)
https://uxmovement.com/navigation/why-users-arent-clicking-your-home-page-carousel/

**Comment by Gilpop8663** [comment]
공지사항을 캐러셀로 보여주지 않기로 하여 이슈를 닫습니다
