### ISSUE TITLE
[BUG] 토스트 위치 이상해요. 왼쪽 하단으로 이동됨

### ISSUE THREAD

**Issue by chsua** [woowacourse-teams/2023-votogether#647]
### 버그 사항
토스트 위치 이상해요. 왼쪽 하단으로 이동됨
 

### 버그 simulation
에러 발생 시 나타나는 토스트가 왼쪽 하단으로 이동됨
카테고리에서 나는 오류와 게시글에서 나는 오류의 토스트 위치가 다름
 

### 원하던 상황
중앙 하단으로 이동했으면..
동일한 위치에 나타났으면...
 

### **Screenshots**
<img width="1680" alt="스크린샷 2023-09-19 오후 5 31 33" src="https://github.com/woowacourse-teams/2023-votogether/assets/113416448/68d4ed4c-ce93-4a6f-a4ba-2e7327d4bd12">

**Comment by inyeong-kang** [comment]
요거 https://github.com/woowacourse-teams/2023-votogether/issues/635 여기 이슈에서 해결해서 pr 올라가 있습니다!
