### ISSUE TITLE
[BUG] 배너를 닫고 다른 페이지로 갔다가 홈으로 들어와있을 때 계속 열려있어요

### ISSUE THREAD

**Issue by inyeong-kang** [woowacourse-teams/2023-votogether#707]
### 버그 사항
배너를 닫고 다른 페이지로 갔다가 홈으로 들어와 있을 때 계속 열려있어 불편합니다.
 

### 버그 simulation
1. 배너를 취소버튼을 눌러 닫는다.
2. 홈에서 다른 페이지로 이동한다.
3. 다른 페이지에서 홈으로 왔을 때 배너가 계속 열려 있다.

### 원하던 상황
배너를 한번 닫으면, 다른 페이지에서 홈으로 왔을 때 배너가 닫혀있도록 합니다. 
혹은 쿠키를 이용하여 만료 시간이 지난 후에 다시 배너가 열리도록 합니다.

**Comment by Gilpop8663** [comment]
### 구현 내용
- 배너를 닫았을 경우 1시간동안 안보이도록 쿠키 설정

### 상세 내용
- 배너를 닫았을 경우 useContext를 사용하기엔 코드 사용되는 양이 너무 많다고 생각이 들어서 쿠키를 이용해 1시간만 안보이도록 할 예정
