### ISSUE TITLE
[BUG] 선택지 사진이 정중앙 배치가 아니에요

### ISSUE THREAD

**Issue by Gilpop8663** [woowacourse-teams/2023-votogether#710]
### 버그 사항
선택지 사진이 정중앙 배치가 아니에요
 

### 버그 simulation
상세 게시글 이동 후 선택지 사진 보기
 

### 원하던 상황
선택지의 사진이 정 중앙으로 배치되면 좋겠어요
 

### **Screenshots**

![image](https://github.com/woowacourse-teams/2023-votogether/assets/80146176/a4cff41c-26b5-4895-af98-f76458d6c104)

**Comment by chsua** [comment]
??? 세상에 제가 80%으로 줄이면서 확인 못했나봐요
