### ISSUE TITLE
[BUG] .map 할때 key가 없어서 경고메세지가 뜹니다

### ISSUE THREAD

**Issue by chsua** [woowacourse-teams/2023-votogether#714]
### 버그 사항
.map 할때 key가 없는지 메인 페이지에서 경고메세지가 뜹니다
 

### 버그 simulation
.map 할때 key가 없는지 메인 페이지에서 경고메세지가 뜹니다

### 원하던 상황
깨끗한 화면
 

### **Screenshots**
<img width="546" alt="스크린샷 2023-10-05 오후 3 23 28" src="https://github.com/woowacourse-teams/2023-votogether/assets/113416448/5d28d9c6-9dd6-4e32-bdbc-ebbb7eb72944">

**Comment by Gilpop8663** [comment]
이거 여기 PR에서 해결햇어요

https://github.com/woowacourse-teams/2023-votogether/pull/706
